name: Pull Request Workflow

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
            - DEV

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: initialize docker
              env:
                AWSLOGIN: ${{ secrets.AWSLOGIN }}
              run: echo $AWSLOGIN | docker login --username AWS --password-stdin 533267032079.dkr.ecr.ap-south-1.amazonaws.com
            - name: Run Docker Build and push
              run: |
                cd ./src
                for dir in */; do
                  echo "Building and pushing $dir"
                  docker build -t 533267032079.dkr.ecr.ap-south-1.amazonaws.com/sen/opentelemetry/$dir:${{ github.run_number }} $dir
                done
