name: Pull Request Workflow

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                java-version: '21'
                distribution: 'temurin'
            - name: Setting execution permissions
              run: chmod +x ./gradlew
              working-directory: ./src/ad/
            - name: Set up Gradle Cache
              run: ./gradlew installDist
              working-directory: ./src/ad/
            - name: Upload to AWS CodeArtifact
              env:
                CODEARTIFACT_AUTH_TOKEN: ${{ secrets.uploadtoken }}
              run: |
                ./gradlew publish \
                  -PawsCodeArtifactToken=$CODEARTIFACT_AUTH_TOKEN \
                  -PawsCodeArtifactRepoUrl=https://testdomain-533267032079.d.codeartifact.ap-south-1.amazonaws.com/maven/ad-service/
              working-directory: ./src/ad/