name: Pull Request Workflow

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
            - DEV

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Run Docker Build
              run: docker