name: Pull Request Workflow

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Print Hello WOrld
              run: echo "Hello World"
            - name: Install dependencies gradle
              run: ./src/ad/gradlew dependencies
            - name: Run tests
              run: ./src/ad/gradlew test
            - name: Build the project
              run: ./src/ad/gradlew build
            - name: Run the application
              run: ./src/ad/gradlew bootRun
            - name: Upload the build artifact
              run: echo "Uploading the build artifact"