# name: Pull Request Workflow

# on:
#     pull_request:
#         branches:
#             - main
#     push:
#         branches:
#             - main
#             - DEV

# jobs:
    # build:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@v4
    #         - name: Setup Docker Buildx
    #           uses: docker/setup-buildx-action@v3
    #         - name: initialize docker
    #           env:
    #             AWSLOGIN: ${{ secrets.AWSLOGIN }}
    #           run: docker login --username AWS --password $AWSLOGIN 533267032079.dkr.ecr.ap-south-1.amazonaws.com
    #         - name: Run Docker Build and push
    #           run: |
    #             for dir in */; do
    #               cd "$dir"
    #               dir=${dir%/}
    #               echo "Building and pushing $dir"
    #               docker build -t 533267032079.dkr.ecr.ap-south-1.amazonaws.com/opentelemetry/"$dir":${{ github.run_number }} .|| { echo "Docker build failed for $dir"; cd ..; continue; }
    #               docker push 533267032079.dkr.ecr.ap-south-1.amazonaws.com/opentelemetry/"$dir":${{ github.run_number }} || { echo "Docker push failed for $dir"; cd ..; continue; }
    #               cd ..
    #             done
    #           working-directory: ./src
    #           continue-on-error: true

    # updatek8smanifest:
    #     runs-on: ubuntu-latest
    #     steps:
    #       - name: Checkout
    #         uses: actions/checkout@v4
    #         with:
    #           token: ${{ secrets.GITHUBTOKEN }}
    #       - name: Update Kubernetes Manifests
    #         run: |
    #           for dir in */; do
    #             cd "$dir"
    #             dir=${dir%/}
    #             echo "Updating Kubernetes manifests for $dir"
    #             sed -i "s|image: '.*$dir.*'|image: '533267032079.dkr.ecr.ap-south-1.amazonaws.com/opentelemetry/"$dir":${{ github.run_number }}'|g" deploy.yaml || { echo "Failed to update Kubernetes manifests for $dir"; cd ..; continue; }
    #             cd ..
    #           done
    #         working-directory: ./kubernetes
    #       - name: commit and push to github
    #         run: |
    #           git config --global user.name "Sen"
    #           git config --global user.email "sen@senworld.in"
    #           git add .
    #           git commit -m "Updated Kubernetes manifests with new image tags"
    #           git push remote HEAD:main
    #         working-directory: ./kubernetes
