name: Pull Request Workflow

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                java-version: '21'
                distribution: 'temurin'
            - name: Set up Gradle Cache
              run: ./gradlew installDist
              working-directory: ./src/ad/
              